# Generated by Django 3.1.4 on 2021-02-02 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_themecolorsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThemeColorSettings',
        ),
    ]
