# Generated by Django 3.1.4 on 2021-02-15 04:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.fields
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    replaces = [('locations', '0001_initial'), ('locations', '0002_lat_long'), ('locations', '0003_promoted_pages_and_near_me'), ('locations', '0004_promoted_pages_title_intro'), ('locations', '0005_locationsindexpage_page_theme_color'), ('locations', '0006_auto_20210203_2115'), ('locations', '0007_locationsindexpage_primary_font_color'), ('locations', '0008_auto_20210203_2245'), ('locations', '0009_locationsindexpage_page_background_color'), ('locations', '0010_locationsindexpage_content_card_color'), ('locations', '0011_auto_20210210_0101'), ('locations', '0012_locationpage_address')]

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
        ('wagtailimages', '0022_uploadedimage'),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('date', models.DateField(verbose_name='Creation date')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocationTagIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocationPageTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='locations.locationpage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations_locationpagetag_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationPageGalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='locations.locationpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='locationpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='locations.LocationPageTag', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='longitude',
        ),
        migrations.CreateModel(
            name='LocationsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.core.fields.RichTextField(blank=True)),
                ('max_dist_km', models.IntegerField(default=50, verbose_name='maximum distance (km)')),
                ('show_near_me', models.BooleanField(default=True)),
                ('promoted_pages_intro', wagtail.core.fields.RichTextField(blank=True, verbose_name='Promoted Locations Intro')),
                ('promoted_pages_title', models.CharField(blank=True, max_length=250, verbose_name='Promoted Locations Title')),
                ('page_theme_color', wagtail_color_panel.fields.ColorField(default='#007bf', max_length=7)),
                ('primary_font_family', models.CharField(default="font-family: 'Spartan', sans-serif;", max_length=250, verbose_name='Primary Font Family')),
                ('primary_font_url', models.CharField(default='https://fonts.googleapis.com/css2?family=Spartan:wght@300;600&display=swap', max_length=250, verbose_name='Primary Font URL')),
                ('primary_font_color', wagtail_color_panel.fields.ColorField(default='#000000', max_length=7)),
                ('page_background_color', wagtail_color_panel.fields.ColorField(default='#FFFFFF', max_length=7)),
                ('content_card_color', wagtail_color_panel.fields.ColorField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='lat_long',
            field=models.CharField(blank=True, max_length=30, verbose_name='Latitude, longitude'),
        ),
        migrations.CreateModel(
            name='LocationsIndexPromotedPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoted_pages', to='locations.locationsindexpage')),
                ('promoted_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='locationpage',
            name='fri_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='mon_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='sat_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='sun_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='thu_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='tue_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='wed_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='address',
            field=models.CharField(default='auckland', max_length=250),
        ),
    ]
