# Generated by Django 3.1.4 on 2021-02-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_squashed_0012_locationpage_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationsindexpage',
            name='content_card_color',
        ),
        migrations.RemoveField(
            model_name='locationsindexpage',
            name='page_background_color',
        ),
        migrations.RemoveField(
            model_name='locationsindexpage',
            name='page_theme_color',
        ),
        migrations.RemoveField(
            model_name='locationsindexpage',
            name='primary_font_color',
        ),
        migrations.RemoveField(
            model_name='locationsindexpage',
            name='primary_font_family',
        ),
        migrations.RemoveField(
            model_name='locationsindexpage',
            name='primary_font_url',
        ),
    ]
