# Generated by Django 3.1.4 on 2021-01-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpage',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='longitude',
        ),
        migrations.AddField(
            model_name='locationpage',
            name='lat_long',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
