# Generated by Django 3.1.4 on 2021-01-13 01:20

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_promoted_pages_and_near_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsindexpage',
            name='promoted_pages_intro',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Promoted Locations Intro'),
        ),
        migrations.AddField(
            model_name='locationsindexpage',
            name='promoted_pages_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Promoted Locations Title'),
        ),
    ]
