# Generated by Django 3.1.4 on 2021-01-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_promoted_pages_and_near_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsindexpromotedpage',
            name='promotion_description',
            field=models.CharField(default='promotion desscription goes here', max_length=250),
        ),
        migrations.AddField(
            model_name='locationsindexpromotedpage',
            name='promotion_title',
            field=models.CharField(default='promotion title goes here', max_length=100),
        ),
    ]
