# Generated by Django 3.1.4 on 2021-01-12 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210112_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationsindexpromotedpage',
            name='promotion_description',
        ),
        migrations.RemoveField(
            model_name='locationsindexpromotedpage',
            name='promotion_title',
        ),
        migrations.AddField(
            model_name='locationsindexpage',
            name='promotion_description',
            field=models.CharField(default='promotion desscription goes here', max_length=250),
        ),
        migrations.AddField(
            model_name='locationsindexpage',
            name='promotion_title',
            field=models.CharField(default='promotion title goes here', max_length=100),
        ),
    ]
