# Generated by Django 3.1.4 on 2021-01-08 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210108_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='lat_long',
            field=models.CharField(default='0,0', max_length=25),
        ),
    ]
