# Generated by Django 3.1.4 on 2021-03-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_added_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsindexpage',
            name='custom_css',
            field=models.FileField(default='/uploaded_css/premio_cms.css', upload_to=''),
        ),
    ]
