# Generated by Django 3.1.4 on 2021-01-12 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210112_0051'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCarousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_title', models.CharField(default='location title', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='locationpage',
            name='location_carousel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.locationcarousel'),
        ),
    ]
