# Generated by Django 3.1.4 on 2021-01-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210108_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
