# Generated by Django 3.1.4 on 2021-02-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_locationsindexpage_page_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsindexpage',
            name='primary_font_family',
            field=models.CharField(default="font-family: 'Spartan', sans-serif;", max_length=250, verbose_name='Primary Font Family'),
        ),
        migrations.AddField(
            model_name='locationsindexpage',
            name='primary_font_url',
            field=models.CharField(default='https://fonts.googleapis.com/css2?family=Spartan:wght@300;600&display=swap', max_length=250, verbose_name='Primary Font URL'),
        ),
    ]
