# Generated by Django 3.1.4 on 2021-02-03 22:45

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_locationsindexpage_primary_font_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationsindexpage',
            name='primary_font_color',
            field=wagtail_color_panel.fields.ColorField(default='#000000', max_length=7),
        ),
    ]
