# Generated by Django 3.1.4 on 2021-02-03 22:56

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20210203_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsindexpage',
            name='page_background_color',
            field=wagtail_color_panel.fields.ColorField(default='#FFFFFF', max_length=7),
        ),
    ]
