# Generated by Django 3.1.4 on 2021-02-03 23:03

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_locationsindexpage_page_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationsindexpage',
            name='content_card_color',
            field=wagtail_color_panel.fields.ColorField(default='#FFFFFF', max_length=7),
        ),
    ]
