# Generated by Django 3.1.4 on 2021-02-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0010_locationsindexpage_content_card_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='fri_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='mon_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='sat_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='sun_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='thu_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='tue_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='wed_hours',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
