# Generated by Django 3.1.4 on 2021-02-10 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0011_auto_20210210_0101'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='address',
            field=models.CharField(default='auckland', max_length=250),
        ),
    ]
